FROM golang:1.13-alpine

# Install git
RUN set -ex; \
    apk update; \
    apk add --no-cache git

# Set working directory
WORKDIR /go/src/github.com/delgus/report/

# Run tests
CMD CGO_ENABLED=0 go test -short ./... -coverprofile=coverage.txt