version: '3.5'

services:
  postgres:
    image: postgres
    container_name: reports_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - ${PWD}/init:/docker-entrypoint-initdb.d
    ports:
      - 5000:5432
    networks:
      - postgres
    restart: unless-stopped

  report-server-v1:
    build:
      context: .
      dockerfile: Dockerfile
      target: report1
    container_name: report_v1
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=123456
      - PG_DBNAME=postgres
      - PG_PORT=5432
      - APP_PORT=80
    ports:
      - 8010:80
    networks:
      - postgres

  report-server-v2:
    build:
      context: .
      dockerfile: Dockerfile
      target: report2
    container_name: report_v2
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=123456
      - PG_DBNAME=postgres
      - PG_PORT=5432
      - APP_PORT=80
    ports:
      - 8020:80
    networks:
      - postgres

networks:
  postgres:
    driver: bridge