version: '3.5'

services:
  db-integration:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ${PWD}/init:/docker-entrypoint-initdb.d
    networks:
      - integration-networks

  reporters-integration:
    depends_on:
      - db-integration
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - PG_HOST=db-integration
      - PG_USER=postgres
      - PG_PASSWORD=123456
      - PG_DBNAME=postgres
      - PG_PORT=5432
    command: sh -c "CGO_ENABLED=0 GOOS=linux go test -v -short ./..."
    networks:
      - integration-networks
    restart: on-failure:10

networks:
  integration-networks:
    driver: bridge