version: '3.5'

services:
  postgres:
    image: postgres
    container_name: reports_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - ${PWD}/init:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_VOLUME_PORT}:5432
    networks:
      - postgres
    restart: unless-stopped

  report-server-v1:
    image: golang:1.13
    container_name: reports_server_v1
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=123456
      - PG_DBNAME=postgres
      - PG_PORT=5432
      - APP_PORT=80
    ports:
      - ${REPORT_1_VOLUME_PORT}:80
    volumes:
      - ${PWD}:/go/src/reports
    working_dir: /go/src/reports
    command: ./bin/report1
    networks:
      - postgres

  report-server-v2:
    image: golang:1.13
    container_name: reports_server_v2
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=123456
      - PG_DBNAME=postgres
      - PG_PORT=5432
      - APP_PORT=80
    ports:
      - ${REPORT_2_VOLUME_PORT}:80
    volumes:
      - ${PWD}:/go/src/reports
    working_dir: /go/src/reports
    command: ./bin/report2
    networks:
      - postgres

networks:
  postgres:
    driver: bridge