version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - ${PWD}/init:/docker-entrypoint-initdb.d
    ports:
      - "5000:5432"
    networks:
      - postgres
    restart: unless-stopped

  report-server-v1:
    image: golang:1.13
    ports:
      - "8010:80"
    volumes:
      - ${PWD}:/go/src/reports
    working_dir: /go/src/reports
    command: ./bin/report1
    networks:
      - postgres

  report-server-v2:
    image: golang:1.13
    ports:
      - "8020:80"
    volumes:
      - ${PWD}:/go/src/reports
    working_dir: /go/src/reports
    command: ./bin/report2
    networks:
      - postgres

networks:
  postgres:
    driver: bridge