version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ${PWD}/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  report-server:
    image: golang:1.13
    ports:
      - "8010:8010"
      - "8020:8020"
      - "8030:8030"
    volumes:
      - ${PWD}:/go/src/reports
    working_dir: /go/src/reports
    command: sh -c "./bin/report1 && ./bin/report2 && ./bin/report3"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge