version: '3.5'

services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ${PWD}/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: unless-stopped